(add-to-list 'load-path (concat elisp-dir "/caml"))
(add-to-list 'load-path (concat elisp-dir "/ruby-mode"))
(add-to-list 'load-path (concat elisp-dir "/slime"))
(load (concat elisp-dir "/haskell-mode/haskell-site-file"))
(load (concat elisp-dir "/sml-mode/sml-mode-startup"))
